const state={history:[]};
const hasDOM=typeof document!=='undefined';
const $=s=>hasDOM?document.querySelector(s):null;
const messages=hasDOM?$('#messages'):null,plan=hasDOM?$('#plan'):null,planEmpty=hasDOM?$('#planEmpty'):null,trace=hasDOM?$('#trace'):null,confidence=hasDOM?$('#confidence'):null;
function addMessage(role,text){const el=document.createElement('div');el.className=`bubble ${role}`;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;}
function mins(t){const m=t.match(/(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m)return null;let h=+m[1],mm=+(m[2]||0);if(m[3]){const p=m[3].toLowerCase();if(p==='pm'&&h<12)h+=12;if(p==='am'&&h===12)h=0;}return h*60+mm;}
function fmt(m){let h=Math.floor(m/60),mm=m%60;const p=h>=12?'PM':'AM';h=h%12||12;return `${h}:${String(mm).padStart(2,'0')} ${p}`;}
function analyze(text){const lower=text.toLowerCase();let start=18*60+30,end=22*60+30;const explicit=[...text.matchAll(/(\d{1,2})(?::\d{2})?\s*(?:am|pm)/ig)].map(x=>mins(x[0])).filter(Number.isFinite);if(explicit.length){start=Math.min(...explicit);end=Math.max(...explicit);if(start===end)start=Math.max(0,end-180);}const tasks=[];
 const catalog=[['dinner|cook|meal',45,'Prepare/eat dinner'],['laundry',35,'Run laundry'],['study|homework|read',30,'Focused study'],['exercise|workout',20,'Exercise'],['kitchen',20,'Reset kitchen'],['living room|tidy|clean',15,'Tidy living room'],['snack',10,'Prepare quick snack'],['pack|packing',15,'Pack essentials'],['breakfast',25,'Breakfast'],['shower',15,'Shower / get ready']];
 for(const [pat,dur,label] of catalog){if(new RegExp(pat).test(lower))tasks.push({label,dur});}
 if(!tasks.length)tasks.push({label:'Clarify priorities and create first action',dur:15},{label:'Execute highest-value task',dur:30},{label:'Review and adjust',dur:15});
 const budget=Math.max(30,end-start),total=tasks.reduce((a,t)=>a+t.dur,0);let scale=total>budget?budget/total:1;let cursor=start;const scheduled=tasks.map((t,i)=>{const d=Math.max(10,Math.round(t.dur*scale/5)*5);const s=cursor,e=Math.min(end,s+d);cursor=e+(i<tasks.length-1?5:0);return {...t,start:s,end:e,dur:e-s};});
 const conflicts=[];if(total>budget)conflicts.push(`Requested work needs about ${total} minutes but the available window is about ${budget} minutes, so durations were compressed and lower-priority detail should be deferred.`);if(/without overloading|calm|not overload/.test(lower))conflicts.push('Low-load mode enabled: short buffers are preserved between activities.');
 return {start,end,scheduled,conflicts,assumptions:['Times are treated as local time.','No external devices or purchases are triggered automatically.','Any action with cost, account change, or safety impact requires confirmation.'],confidence:conflicts.length?0.82:0.9};}
function render(result){planEmpty.classList.add('hidden');plan.classList.remove('hidden');confidence.textContent=`${Math.round(result.confidence*100)}% confidence`;plan.innerHTML='';
 const summary=document.createElement('div');summary.className='plan-block';summary.innerHTML=`<h3>Proposed schedule</h3>${result.scheduled.map(t=>`<div class="task"><div class="time">${fmt(t.start)}</div><div><strong>${t.label}</strong><small>${t.dur} min · ends ${fmt(t.end)}</small></div></div>`).join('')}`;plan.appendChild(summary);
 const assumptions=document.createElement('div');assumptions.className='plan-block';assumptions.innerHTML=`<h3>Assumptions</h3>${result.assumptions.map(x=>`<div>• ${x}</div>`).join('')}`;plan.appendChild(assumptions);
 if(result.conflicts.length){const c=document.createElement('div');c.className='plan-block warning';c.innerHTML=`<h3>Conflicts detected</h3>${result.conflicts.map(x=>`<div>• ${x}</div>`).join('')}`;plan.appendChild(c);}
 const gate=document.createElement('div');gate.className='plan-block confirm';gate.innerHTML='<h3>Confirmation gate</h3><div>HomePilot may suggest actions, but it will not spend money, send messages, change accounts, or control safety-sensitive devices without explicit confirmation.</div>';plan.appendChild(gate);
}
function run(text){addMessage('user',text);const r=analyze(text);state.history.push({text,r});const compressed=r.conflicts.some(x=>x.includes('compressed'));addMessage('assistant',compressed?'I found a timing conflict, so I built a compressed plan and surfaced the trade-off instead of pretending everything fits. Review the schedule before confirming any external action.':'I built a deterministic plan with explicit assumptions and a confirmation gate for consequential actions.');render(r);trace.textContent=[`1. Intent parsed: household planning`,`2. Time window inferred: ${fmt(r.start)} → ${fmt(r.end)}`,`3. Candidate tasks extracted: ${r.scheduled.map(x=>x.label).join(', ')}`,`4. Constraint check: ${r.conflicts.length?r.conflicts.length+' issue(s) found':'no conflicts'}`,`5. Schedule built with buffers and bounded durations`,`6. Safety policy applied: consequential external actions require confirmation`].join('\n');}
function boot(){addMessage('assistant','Hi — I’m HomePilot, a simulated Alexa+ household operations agent. Tell me the outcome you want and your constraints; I’ll build an editable plan and show my assumptions.');}
if(hasDOM){$('#chatForm').addEventListener('submit',e=>{e.preventDefault();const v=$('#prompt').value.trim();if(v){run(v);$('#prompt').value='';}});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>run(b.dataset.prompt)));$('#resetBtn').addEventListener('click',()=>{messages.innerHTML='';plan.innerHTML='';plan.classList.add('hidden');planEmpty.classList.remove('hidden');trace.textContent='No run yet.';confidence.textContent='Ready';boot();});boot();}
if(typeof module!=='undefined')module.exports={analyze,mins,fmt};